import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

import { FileUploader } from "react-drag-drop-files";
import useAxios from "axios-hooks";

import { FaGithub, FaFileUpload } from "react-icons/fa";
import {SiBuymeacoffee} from "react-icons/si"
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });
const fileTypes = ["rosz"];
const bs2ttsBackendUrl =
  "https://bs2tts2pwqnfvyw-bs2tts2-backend.functions.fnc.fr-par.scw.cloud/roster";

function DragDrop() {
  const [{ data, loading, error }, request] = useAxios(
    {
      url: bs2ttsBackendUrl,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
    },
    { manual: true }
  );

  const handleChange = async (files: File) => {
    console.log(files);

    const form = new FormData();
    form.append("roster", files);

    await request({
      data: form,
    });
  };

  return (
    <>
      <FileUploader handleChange={handleChange} name="file" types={fileTypes}>
        <label htmlFor="roster-file" className={styles.mainUpload}>
          <FaFileUpload /> Upload roster file (.rosz)
        </label>
      </FileUploader>
      <div className={styles.status}>
        {loading && <span>Loading...</span>}
        {error && <span>Error: {error.message}</span>}
        {data && (
          <span
            className={styles.rosterId}
            onClick={() => {
              navigator.clipboard.writeText(data.id);
            }}
          >
            {data.id}
          </span>
        )}
        <div className={styles.tooltip}>Click to copy</div>
      </div>
    </>
  );
}

function Footer() {
  return (
    <footer className={styles.footer}>
      <nav>
        <ul>
          <li>
            <a rel="norefferrer" href="https://github.com/sashman/bs2tts/issues/new">
              <FaGithub/> Report Issues
            </a>
          </li>
          <li>
            <a rel="norefferrer" href="https://www.buymeacoffee.com/sashman">
              <SiBuymeacoffee/> Support by donating
            </a>
          </li>
        </ul>
      </nav>
    </footer>
  );
}

export default function Home() {
  return (
    <div className={styles.layout}>
      <Head>
        <title>BS2TTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Image src="bs2tts.png" alt="Battlescribe to Tabletop Simulator logo" 
              width={415}
              height={258}
              />
          <h1>BS2TTS</h1>
          <p> Battlescribe to Tabletop Simulator</p>
        </div>

        <div>
          <DragDrop />
        </div>
      </main>
      <Footer />
    </div>
  );
}
